azerothcore/mod-eluna

GlobalMethods.h
HttpManager.cpp
HttpManager.h
LuaEngine.cpp
LuaEngine.h
LuaFunctions.cpp
ServerHooks.cpp
libs/httplib.h
libs/rigtorp/SPSCQueue.h

This PR adds the possibility to perform HTTP/HTTPS requests in a non-blocking way (they are queued up and executed one by one in a separate thread). The requests can be executed via the `HttpRequest` global function.
Example usage, from the function's docs:
```lua
-- GET example (prints a random word)
HttpRequest("GET", "https://random-word-api.herokuapp.com/word", function(status, body, headers)
print("Random word: " .. string.sub(body, 3, body:len() - 2))
end)
-- POST example with JSON request body
HttpRequest("POST", "https://jsonplaceholder.typicode.com/posts", '{"userId": 1,"title": "Foo","body": "Bar!"}', "application/json", function(status, body, headers)
print(body)
end)
-- Example with request headers
HttpRequest("GET", "https://postman-echo.com/headers", { Accept = …
```

feat: add HttpRequest method

---

docs/ElunaDoc/__main__.py
docs/ElunaDoc/parser.py

This allows building the web documentation with Python 3 instead of Python 2.
The build process stays the same (see [DOC_GEN.md](/azerothcore/Eluna/blob/master/docs/DOC_GEN.md)):
```sh
$ cd LuaEngine/docs/
$ python -m ElunaDoc
```
Pre-requisites:
```
$ python -m pip install jinja2 typedecorator markdown
```

docs: port docs generator to python3

---

ChatHandlerMethods.h
GlobalMethods.h
Hooks.h
LuaEngine.h
LuaFunctions.cpp
PlayerHooks.cpp

* Adds class `ChatHandler`
* `GetPlayer()`
* `GetSelectedCreature()`
* `GetSelectedObject()`
* `GetSelectedPlayer()`
* `GetSelectedPlayerOrSelf()`
* `GetSelectedUnit()`
* `HasLowerSecurity()`
* `HasLowerSecurityAccount()`
* `HasSentErrorMessage()`
* `IsAvailable()`
* `IsConsole()`
* `SendGlobalGMSysMessage()`
* `SendGlobalSysMessage()`
* `SendSysMessage()`
* Adds `ChatHandler` argument passed to `PLAYER_EVENT_ON_COMMAND` hook
* The arguments are now `(event, player, command, chatHandler)`
* Example usage:
```lua
local PLAYER_EVENT_ON_COMMAND = 42
RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, function(event, player, text, chatHandler)
if text ~= "testcmd" then
return true
end
if not chatHandler:IsAvailable(3) then
-- Restrict usage to sec level 3 and higher
return true
end …
```

feat: add chat handler methods

---

.github/workflows/create-pr.sh
.github/workflows/documentation.yml

Re-adds the workflow from https://github.com/azerothcore/mod-eluna/pull/22
This adds a Github action to automatically push the changes made to the documentation to [azerothcore/azerothcore.github.io](https://github.com/azerothcore/azerothcore.github.io/tree/master/pages/eluna) in the form of a pull request

ci: re-add docs workflow

---

src/LuaEngine/GameObjectMethods.h
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/ObjectMethods.h

Exposed/added functions/methods:
- IsPlayer()
~~- Object:AddLoot(entry,amount)~~

expose IsPlayer()

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Added OnLearnSpell(player, spellId)
Example:
```LUA
local PLAYER_EVENT_ON_LEARN_SPELL = 44
local function TestOnLearnSpell(event, player, spellid)
player:SendBroadcastMessage('You just learned spell id '..spellid)
end
RegisterPlayerEvent(PLAYER_EVENT_ON_LEARN_SPELL, TestOnLearnSpell)
```

feat(PlayerHooks): OnLearnSpell(player, spellid)

---

src/LuaEngine/PlayerMethods.h

Updated SendListInventory to allow specifying which vendor entry to send to the player.
Tested with a creature template entry of 9000000 with 129 set as npcflag and with a npc_vendor entry. The first option opens the vendor offered by the stormwind innkeeper while the second one defaults to the creature you're talking to.
```lua
local function VendorOnGossipHello(event, player, object)
player:GossipClearMenu()
player:GossipMenuAddItem(7, "I want something", 1, 100)
player:GossipMenuAddItem(7, "I want something else", 1, 200)
player:GossipSendMenu(0x7FFFFFFF, object, 1)
end
local function VendorOnGossipSelect(event, player, object, sender, intid, code, menu_id)
if (intid == 100) then
player:SendListInventory(object, 6740) -- entry 6740 from npc_vendor
elseif (intid == 200) then …
```

feat(Core/Player): SendListInventory with vendor id

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/AchievementMethods.h
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerHooks.cpp

- Added AchievementMethods
- Added GetId to AchievementMethods
- Added OnAchiComplete to PlayerHooks
Tested with:
```lua
local PLAYER_ON_ACHIEVEMENT_COMPLETE = 45
local function OnAchiComplete(event, player, achievement)
print(player:GetName()..' has completed achievement with id '..achievement:GetId())
end
RegisterPlayerEvent(PLAYER_ON_ACHIEVEMENT_COMPLETE, OnAchiComplete)
```
Note: I wanted to add GetName() to AchievementMethods but locale kept causing a segmentation fault so I'm holding off on that for now

feat(Core): Achievements

---

src/LuaEngine/GameObjectMethods.h
src/LuaEngine/LuaFunctions.cpp

Adds a new method to gameobjects, which allows spawning loot at runtime in an **empty** container.
Co-authored by @r-o-b-o-t-o 
Tested with:
```SQL
##Copy of the Arena Chest with 0 loot
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES ('510001', '3', '259', 'Treasure Chest', '', '', '', '1', '1599', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0');
```
```lua
local …
```

feat: GameObject:AddLoot()

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Co-authored by https://github.com/DavuKnight
Tested with
```lua
local function OnFfaPvpChange(event, player, hasFfaPvp)
print('Firing OnFfaPvpChange')
if player then
print( player:GetName() )
print(hasFfaPvp)
end
end
RegisterPlayerEvent(46, OnFfaPvpChange)
```

feat: add player event OnFfaPvpStateUpdate

---

conf/mod_LuaEngine.conf.dist
src/LuaEngine/LuaEngine.cpp

Closes #61 
By default set to send to >0 security players.

Add config option to send reload message to non-0 security level players.

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerMethods.h

Adds `Player:GetAchievementCriteriaProgress()`:
> Returns the progress of the player for the specified achievement criteria.
**Requires https://github.com/azerothcore/azerothcore-wotlk/pull/14387**

feat: add Player:GetAchievementCriteriaProgress()

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerMethods.h

Adds `Player:GetMailCount()`:
> Returns the amount of mails in the player's mailbox.

feat: add Player:GetMailCount()

---

src/LuaEngine/GlobalMethods.h

Log commands output with `ELUNA_LOG_INFO()` when using [`RunCommand()`](https://www.azerothcore.org/pages/eluna/Global/RunCommand.html).

feat: log commands output

---

src/LuaEngine/GlobalMethods.h

Fixes the following build warning:
> In file included from /home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:20:
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/GlobalMethods.h:1232:81: fatal error: unused parameter 'obj' [-Wunused-parameter]
eWorld->QueueCliCommand(new CliCommandHolder(nullptr, command, [](void* obj, std::string_view view)
^
1 error generated.

fix: modules ci build

---

src/LuaEngine/GlobalMethods.h
src/LuaEngine/LuaFunctions.cpp

Co-authored by @r-o-b-o-t-o 
Adds new Global methods:
SetOwnerHalaa($teamId) //0=Alliance, 1 = Horde
GetOwnerHalaa() // returns { 0 or 1 for owner, $slider }
Tested with:
```lua
local function command( event, player, command, chathandler )
if command == 'yx' then
chathandler:SendSysMessage('SetOwnerHalaa(0)')
SetOwnerHalaa(0)
elseif command == 'as' then
chathandler:SendSysMessage('SetOwnerHalaa(1)')
SetOwnerHalaa(1)
elseif command == 'qw' then
chathandler:SendSysMessage('SetOwnerHalaa(2)')
SetOwnerHalaa(2)
elseif command == 'asdf' then
local owner
local slider
owner, slider = GetOwnerHalaa()
chathandler:SendSysMessage('GetOwnerHalaa(): '..owner..' slider: '..slider)
end
return false
end
RegisterPlayerEvent(42, command)
```

feat: add getter and setter for halaa ownership

---

src/ElunaLuaEngine_SC.cpp

`GROUP_EVENT_ON_CREATE` from [`RegisterGroupEvent`](https://www.azerothcore.org/pages/eluna/Global/RegisterGroupEvent.html) was never called.

fix: call the group OnCreate hook

---

README.md
src/LuaEngine/GlobalMethods.h
src/LuaEngine/ItemMethods.h
src/LuaEngine/ItemTemplateMethods.h
src/LuaEngine/LuaFunctions.cpp

* Adds `GetItemTemplate(itemEntry)`
* Adds `Item:GetItemTemplate()`
* Adds `ItemTemplate` methods:
* `ItemTemplate:GetItemId()`
* `ItemTemplate:GetClass()`
* `ItemTemplate:GetSubClass()`
* `ItemTemplate:GetName()`
* `ItemTemplate:GetDisplayId()`
* `ItemTemplate:GetQuality()`
* `ItemTemplate:GetFlags()`
* `ItemTemplate:GetExtraFlags()`
* `ItemTemplate:GetBuyCount()`
* `ItemTemplate:GetBuyPrice()`
* `ItemTemplate:GetSellPrice()`
* `ItemTemplate:GetInventoryType()`
* `ItemTemplate:GetAllowableClass()`
* `ItemTemplate:GetAllowableRace()`
* `ItemTemplate:GetItemLevel()`
* `ItemTemplate:GetRequiredLevel()`
Most of these methods are still accessible through the `Item` class to keep compatibility with existing scripts.

feat: add ItemTemplate methods

---

README.md
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Adds a new `Player` event:
```cpp
PLAYER_EVENT_ON_CAN_INIT_TRADE = 48, // (event, player, target) - Can return false to prevent the trade
```
```lua
local PLAYER_EVENT_ON_CAN_INIT_TRADE = 48
local function OnTrade(event, player, target)
print(player:GetName() .. " initiated a trade with " .. target:GetName())
return false -- prevent the trade
end
RegisterPlayerEvent(PLAYER_EVENT_ON_CAN_INIT_TRADE, OnTrade)
```

feat: add PLAYER_EVENT_ON_CAN_INIT_TRADE

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Adds a new `Player` event:
```cpp
PLAYER_EVENT_ON_CAN_SEND_MAIL = 49, // (event, player, receiverGuid, mailbox, subject, body, money, cod, item) - Can return false to prevent sending the mail
```
```lua
local PLAYER_EVENT_ON_CAN_SEND_MAIL = 49
local function OnSendMail(event, player, receiverGuid, mailbox, subject, body, money, cod, item)
local receiver = GetPlayerByGUID(receiverGuid)
if (receiver ~= nil) then
print(player:GetName() .. " wants to send a mail to " .. receiver:GetName())
else
print(player:GetName() .. " wants to send a mail to " .. tostring(receiverGuid))
end
print("Subject: " .. subject)
if money > 0 then
print("Attached: " .. tostring(money) .. " copper")
end
if item ~= nil then
print("Attached: " .. item:GetName())
end
if cod > 0 then
print("COD: " …
```

feat: add PLAYER_EVENT_ON_CAN_SEND_MAIL

---

README.md
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Adds a new `Player` event:
```cpp
PLAYER_EVENT_ON_CAN_JOIN_LFG = 50, // (event, player, roles, dungeons, comment) - Can return false to prevent queueing
```
```lua
local PLAYER_EVENT_ON_CAN_JOIN_LFG = 50
RegisterPlayerEvent(PLAYER_EVENT_ON_CAN_JOIN_LFG, function(event, player, roles, dungeons, comment)
print("Player: " .. player:GetName())
print("Roles: " .. tostring(roles))
print("Dungeons:")
for i = 1, #dungeons do
print(dungeons[i])
end
if (comment ~= nil) then
print("Comment: " .. comment)
end
return false -- prevent queueing
end)
```

feat: add PLAYER_EVENT_ON_CAN_JOIN_LFG

---

README.md
README_CN.md
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

add PLAYER_EVENT_ON_QUEST_REWARD_ITEM
add PLAYER_EVENT_ON_CREATE_ITEM
add PLAYER_EVENT_ON_STORE_NEW_ITEM

feat: add PLAYER_EVENT_ON_QUEST_REWARD_ITEM, add PLAYER_EVENT_ON_CREATE_ITEM, add PLAYER_EVENT_ON_STORE_NEW_ITEM

---

README.md
README_CN.md
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Adds a new Player event:
PLAYER_EVENT_ON_COMPLETE_QUEST = 54, // (event, player, quest)
local PLAYER_EVENT_ON_COMPLETE_QUEST = 54
RegisterPlayerEvent(PLAYER_EVENT_ON_COMPLETE_QUEST, function(event, player, quest)
print("Player: " .. player:GetName())
print("QuestID: " .. quest:GetId())
end)

feat: add PLAYER_EVENT_ON_COMPLETE_QUEST

---

README.md
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Adds a new `Player` event:
```cpp
PLAYER_EVENT_ON_CAN_GROUP_INVITE = 55 // (event, player, memberName) - Can return false to prevent inviting
```
```lua
local PLAYER_EVENT_ON_CAN_GROUP_INVITE = 55
RegisterPlayerEvent(PLAYER_EVENT_ON_CAN_GROUP_INVITE, function(event, player, newMemberName)
print("Player: " .. player:GetName())
print("Invited: " .. newMemberName)
return false -- prevent inviting
end)
```

feat: add PLAYER_EVENT_ON_CAN_GROUP_INVITE

---

README.md
src/LuaEngine/GroupMethods.h
src/LuaEngine/LuaFunctions.cpp

Adds `Group:SetMemberFlag(target, apply, flag)`:
Sets or removes a flag for a `[Group]` member
```
enum GroupMemberFlags
{
MEMBER_FLAG_ASSISTANT   = 0x01,
MEMBER_FLAG_MAINTANK    = 0x02,
MEMBER_FLAG_MAINASSIST  = 0x04,
};
```
Arguments:
`ObjectGuid` target : GUID of the target
`bool` apply : add the `flag` if `true`, remove the `flag` otherwise
`[GroupMemberFlags]` flag : the flag to set or unset

feat: add Group:SetMemberFlag()

---

src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/PlayerHooks.cpp

Now returns the channel's database id as a negative number if the channel is custom (otherwise it could return the same id as a regular channel). Same behaviour as before for normal channels.
Requires https://github.com/azerothcore/azerothcore-wotlk/pull/15232
Fixes #98

fix: channel id in PLAYER_EVENT_ON_CHANNEL_CHAT

---

src/ElunaLuaEngine_SC.cpp

Timed events tied to players are removed when a player teleports from one map to another.
In this PR we change it so that timed evens are no longer removed.
See
* https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/a0d10f8ff0e68cf59cd7b2fd62e985adaeb35d9d
* https://discord.com/channels/817077195817353226/1074254244561031248/1074254244561031248

Fix player timed events not carrying over between maps

---

.github/workflows/create-pr.sh

This will prevent creating "empty" PRs when only the date changes, ie. https://github.com/azerothcore/azerothcore.github.io/commit/9f62d5bbab73fd0eb67e60b3d859fd348b54584b

fix(ci): exclude date.js from doc PR git status

---

src/LuaEngine/ItemMethods.h

Fixes https://github.com/azerothcore/mod-eluna/issues/112

fix: GetItemLink crash

---

README.md
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/ItemMethods.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerHooks.cpp
src/LuaEngine/RollMethods.h

* Closes https://github.com/azerothcore/mod-eluna/issues/99
* Adds a new `Player` event:
```cpp
PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM  =     56,       // (event, player, item, count, voteType, roll)
```
* Adds `Roll` methods:
* `Roll:GetItemGUID`
* `Roll:GetItemId`
* `Roll:GetItemRandomPropId`
* `Roll:GetItemRandomSuffix`
* `Roll:GetItemCount`
* `Roll:GetPlayerVote`
* `Roll:GetPlayerVoteGUIDs`
* `Roll:GetTotalPlayersRolling`
* `Roll:GetTotalNeed`
* `Roll:GetTotalGreed`
* `Roll:GetTotalPass`
* `Roll:GetItemSlot`
* `Roll:GetRollVoteMask`
```lua
local PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM = 56
RegisterPlayerEvent(PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM, function(event, player, item, count, voteType, roll)
local voteTypes = {}
voteTypes[0] = "PASS"
voteTypes[1] = "NEED" …
```

feat: add PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM and roll methods

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/PlayerHooks.cpp

Includes the new XPSource parameter for the OnGiveXP hook.
This PR should only be merged when the core PR is merged.
https://github.com/azerothcore/azerothcore-wotlk/pull/16109
- Create ./lua_scripts/TestXPHook.lua
```lua
local PLAYER_EVENT_ON_GIVE_XP = 12
xpMap = {}
xpMap[0] = "Kill"
xpMap[1] = "Quest"
xpMap[2] = "Dungeon Finder"
xpMap[3] = "Explore"
xpMap[4] = "Battleground"
local function OnGiveXP(event, player, amount, victim, source)
player:SendBroadcastMessage("Received XP from: " .. xpMap[source])
end
RegisterPlayerEvent(PLAYER_EVENT_ON_GIVE_XP, OnGiveXP)
```

fix: Include new parameter for OnGiveXP hook.

---

README.md
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/CreatureMethods.h
src/LuaEngine/GlobalMethods.h
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerHooks.cpp

Implemented the stated methods to the source... tested them... they worked fine! =D
#138

Feature: Added GetUnitFlags(), GetUnitFlagsTwo(), SetUnitFlags(flags), SetUnitFlagsTwo(flags), Added PlayerEvent OnApplyAura/OnRemoveAura

---

src/LuaEngine/GlobalMethods.h

VendorRemoveAllItems deletes while traversing, causing the iterator itr to fail, which causes the worldserver to crash.

Fix crash caused by VendorRemoveAllItems

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerMethods.h

Adds a Method to the Lua Player Object which allows to set Glyphs for the current TalentGroup/Spec
Compiles: yes
Tested: yes
Test Instructions/example Usage:
1. Create/Use a Paladin (works with every class, but the Glyphs I use in this example are for Paladin)
2. add the following lua example to your lua_scripts folder: 
```
local function OnPlayerCommand(event, player, command)
if (command == "add_glyph") then
print("reached_command: add glyph")
player:SetGlyph(190,0)
player:SetGlyph(702,3)
return false
end
end
RegisterPlayerEvent(42, OnPlayerCommand)
```
3. go ingame, write command .add_glyphs - go to TalentUI, section Glyphs: 2 Glyphs have been set into slot 0 and 3
4. (optional) you can log out and login again if you wan to check if they are persisted in the database.

Add Method to Player: SetGlyph

---

README.md
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/UnitMethods.h

Fixxed: SetSpeed and GetSpeed Function
Added: SetSpeedRate and GetSpeedRate
Removed: Unnecessary Ifdef's
Foe recognized on the azerothcore mod-eluna repo that the SetSpeed function is using the wrong SetSpeedRate member of unit.
This PR changes that and seperates the functions from each other.
Also we decided to remove the ifdefs that are not needed as the module is only for azerothcore and not for Trinty or Mangos.
You can test this PR by using the functions in a script and check the impact ;) 
Thanks for your time!

fix(core/func): GetSpeedRate + SetSpeedRate + ifdefs

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerMethods.h

This Pull Request introduces four new methods to the Player class in order to check for a player's specialization:
- HasTankSpec: This method will return true if the player has a Tank Specialization, false otherwise.
- HasMeleeSpec: This method will return true if the player has a Melee Specialization, false otherwise.
- HasCasterSpec: This method will return true if the player has a Caster Specialization, false otherwise.
- HasHealSpec: This method will return true if the player has a Heal Specialization, false otherwise.
The code for these methods has already been tested and works as expected. You can use them by calling Player:HasTankSpec(), Player:HasMeleeSpec(), Player:HasCasterSpec(), Player:HasHealSpec() respectively.
Your feedback on this addition would be greatly appreciated. …

Add Specialization Check Methods to Player

---

.gitignore
src/ElunaLuaEngine_SC.cpp
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerHooks.cpp
src/LuaEngine/PlayerMethods.h

1:
Player:GetAchievementPoints
2:
Player:GetCompletedQuestsCount
This should have been GetCompletedQuestsCount, not sure how to update that now.
3: You also have an option to include feats of strength or not (not included by default, blizzard like)
Player:GetCompletedAchievementsCount
4: RegisterPlayerEvent
OnCreatureKilledByPet

Add 4 methods

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerMethods.h

Hello,
In this pull request we are introducing the SetSpellPower method for Player in the Eluna module.
Here's a brief overview of the function:
```cpp
/**
* The [Player] sets the spell power
*
* @param int value : The spell power value to set
* @param bool apply = false : Whether the spell power should be applied or removed
*/
int SetSpellPower(lua_State* L, Player* player)
{
// Function implementation...
}
```
This allows you to set the spell power of a [Player], indicating the spell power value to set and whether the spell power should be applied or removed.
Tests were carried out over several months on my own server.
Your feedback on this addition would be greatly appreciated.
Kind Regards,
Vaiocti (iThorgrim)

Adding SetSpellPower for Player

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/UnitMethods.h

Greetings,
This pull request introduces the HandleStatModifier method for Unit in the Eluna module.
Here's a brief overview of the addition:
```cpp
/**
* The [Unit] modifies a specific stat
*
* @param int32 stat : The stat to modify
* @param int8 type : The type of modifier to apply
* @param float value : The value to apply to the stat
* @param bool apply = false : Whether the modifier should be applied or removed
* @return bool : Whether the stat modification was successful
*/
int HandleStatModifier(lua_State* L, Unit* unit)
{
// Implementation...
}
```
This new method allows you to modify a specific stat of a [Unit], defining the type of modifier to apply, the value to apply to the stat, and whether the modifier should be applied or removed.
Your feedback on this addition would be …

Adding HandleStatModifier for Unit

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/UnitMethods.h

Adds a new method to add and remove mechanic immunities.
Tested with:
```lua
local function ImmunityOff(eventid, delay, repeats, creature)
creature:SetImmuneTo(26, false)
creature:SendUnitSay("I am interruptable now.", 0)
end
local function Cast(eventid, delay, repeats, creature)
creature:CastSpell(creature, 57775, false)
end
local function EnterCombat(event, creature, target)
creature:SetImmuneTo(26, true)
creature:SendUnitSay("You can not interrupt me.", 0)
creature:RegisterEvent(Cast, 5500, 0)
creature:RegisterEvent(ImmunityOff, 15000, 1)
end
local function LeaveCombat(event, creature)
creature:RemoveEvents()
end
RegisterCreatureEvent(113, 1, EnterCombat)
RegisterCreatureEvent(113, 2, LeaveCombat) -- OnLeaveCombat
RegisterCreatureEvent(113, 4, LeaveCombat) -- OnDied
```

add unit method SetImmuneTo

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/SpellMethods.h

Returns a table containing the reagent cost of the spell in the format
```lua
reagents = {
[ItemTemplate] = amount,
[ItemTemplate] = amount,
...
}
```
Example usage:
```lua
local function OnSpellCast(_, player, spell, _)
local reagents = spell:GetReagentCost()
player:SendBroadcastMessage("You just cast " .. spell:GetEntry() .. " with the following reagents:")
for reagent, count in pairs(reagents) do
player:SendBroadcastMessage(string.format("%d x %s", count, reagent:GetName()))
end
return false
end
RegisterPlayerEvent(PLAYER_EVENT_ON_SPELL_CAST, OnSpellCast)
```

Add Spell:GetReagentCost() function

---

src/LuaEngine/CreatureMethods.h
src/LuaEngine/LuaFunctions.cpp

Introduces the GetRank method. Rank is used in creature_template to set the rank of the creature, e.g. rare (4) or rare elite (2).
You can test this in game with this lua script:
```lua
local command = "#rank"
local function FetchCreatureRank(event, player, message, type, language)
if message == command then
local creature = player:GetSelection() -- Get the player's target
if creature then
local rank = creature:GetRank() -- Fetch the rank of the selected creature
if rank then
print("Creature Rank: " .. rank) -- Print the creature's rank
else
print("Creature rank not available.")
end
else
print("No creature selected.")
end
return false -- Prevent the default chat behavior
end
end
RegisterPlayerEvent(18, FetchCreatureRank)
```
If the player types "#rank" while having targeted a creature, …

feat: add GetRank method for creatures

---

src/LuaEngine/GlobalMethods.h
src/LuaEngine/LuaFunctions.cpp

This allows scripts to be written with compatibility mode checks in place between the different implementations
Until AC supports multistate, these will return the same values as stock Eluna with compatibility mode enabled

Add multistate compatibility methods

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerMethods.h

adds player:GetGlyph(slotIndex) (requested by @55Honey in https://github.com/azerothcore/mod-eluna/issues/152#issuecomment-1669529044_)
add a scripting file with:
``` lua
local function OnPlayerCommand(event, player, command)
if (command == "add_glyph") then
print("reached_command: add glyph")
player:SetGlyph(190,0)
player:SetGlyph(702,3)
player:Say("glyph in slot 0: "..player:GetGlyph(0),0)
player:Say("glyph in slot 1: "..player:GetGlyph(1),0)
player:Say("glyph in slot 3: "..player:GetGlyph(3),0)
return false
end
end
RegisterPlayerEvent(42, OnPlayerCommand)
```
On a paladin execute command ".add_glyph" in chat
Check that output matches input as written in script (190,0,702)
also credit to @kissingers who created a PR on this topics on the same day. …

feature: Add GetGlyph

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/PlayerMethods.h

Adds a possibility to run a command from Script as if the player typed it into the chat himself. This differs from Global:RunCommand in the sense that Global:RunCommand executes Command as if it was typed into the server console, thus ignoring command permissions and also "loosing information" like target, player, position etc. By using player:RunCommand this can be preserved.
In player:RunCommand all permissions checks are asserted as normal.
My usecase for this was that I wanted to create a simple UI for the IndividualXP module by using a gossip menu where players can select their prefered expirience rate.

add player:RunCommand

---

src/LuaEngine/PlayerMethods.h

closes https://github.com/azerothcore/mod-eluna/issues/118
How to Test: 
use this code to verify server doesn't crash after attempting to add more than 32 GossipMenuItems
``` lua
local function hello(event, player, object)
for n = 1, 40, 1 do
player:GossipMenuAddItem(1, "Text "..n, 20124, n)
print("added: "..n)
end
player:GossipSendMenu(0, object, 0)
end
RegisterCreatureGossipEvent(20124, 1, hello)
```
(Code copied from @55Honey in the issue linked above)
Expected Output in world-server console:

Fix gossip menu item overflow

---

src/LuaEngine/ElunaQueryMethods.h

```
In file included from modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:29:
modules/mod-eluna/src/LuaEngine/ElunaQueryMethods.h:32:13: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
32 |             sprintf(arr, "trying to access invalid field index %u. There are %u fields available and the indexes start from 0", field, count);
|             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/_stdio.h:274:1: note: 'sprintf' has been explicitly marked deprecated here
274 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns …
```

sprintf to snprintf (deprecated  MacOSX15.0)

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.cpp
src/LuaEngine/LuaEngine.h
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/hooks/PlayerHooks.cpp
src/LuaEngine/hooks/SpellHooks.cpp
src/LuaEngine/methods/GlobalMethods.h

This pull request integrates the `RegisterSpellEvent` system from the [TrinityCore version of Eluna](https://github.com/ElunaLuaEngine/Eluna/commit/c952ad5596f5333dfa92e475537882cf838a7258) into AzerothCore, allowing scripts to handle specific spell-related events.
1. **`SPELL_EVENT_ON_PREPARE`**  
Triggered when a spell is prepared.  
**Signature**: `(event, caster, spell)`
2. **`SPELL_EVENT_ON_CAST`**  
Triggered when a spell is cast.  
**Signature**: `(event, caster, spell, skipCheck)`
3. **`SPELL_EVENT_ON_CAST_CANCEL`**  
Triggered when a spell cast is canceled.  
**Signature**: `(event, caster, spell, bySelf)`
```lua
lcoal SPELL_EVENT_ON_PREPARE = 1
local function OnSpellPrepare(event, caster, spell)
print("RegisterSpellEvent :: OnPrepare")
end
RegisterSpellEvent(133, …
```

Feat(LuaEngine/SpellHooks): Add support for RegisterSpellEvent with initial events

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/GuildMethods.h

This pull request introduces a series of new API functions for the Guild system in mod-Eluna. 
The new features include methods for setting guild names, updating member data, sending messages, handling guild bank transactions, and more.
- **`SetName`**: Updates the name of a specific guild.
- **`UpdateMemberData`**: Updates a player’s data in the guild member list.
- **`SendMessage`**: Sends a message to the guild from a specific player, with support for officer-only messages and languages.
- **`MassInviteToEvent`**: Invites guild members to events based on level and rank filters.
- **`SwapItems`**: Transfers items between tabs and slots in the guild bank.
- **`SwapItemsWithInventory`**: Allows swapping of items between the guild bank and a player’s inventory.
- **`ModifyBankMoney`**: …

Feat(Methods/Guild): Add new Guild methods

---

src/LuaEngine/ElunaIncludes.h
src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/GlobalMethods.h
src/LuaEngine/methods/SpellInfoMethods.h

This pull request introduces SpellInfo API in mod-Eluna. With the addition of numerous new methods, this update provides developers with enhanced flexibility and control over spell-related interactions.
1. **Localization Support**:
- **`GetName`**: Retrieve spell names in different locales, making localization more accessible.
2. **Attributes and Mechanics**:
- **`HasAttribute`**: Check if a spell has a specific attribute.
- **`GetAttributes`**: Retrieve all attributes of a spell.
- **`IsAffectingArea`**: Determine if a spell affects an area (AoE).
- **`GetCategory`**: Retrieve the spell’s category.
- **`IsPositive` / `IsPositiveEffect`**: Identify whether a spell or its effects are beneficial.
3. **Targeting Enhancements**:
- **`CheckTarget`** and **`CheckExplicitTarget`**: Validate if a …

Feat(LuaEngine/SpellInfo): Add SpellInfo class and methods

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/GameObjectMethods.h

This pull request introduces one new methods in `mod-eluna` for `GameObject`:
- `SetRespawnDelay`
Sets the respawn delay for a gameobject to a specific value.
```lua
gameobject:SetRespawnDelay(30)
```

Feat(LuaEngine/GameObjectMethods): Add SetRespawnDelay

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/MapMethods.h

This pull request introduces two new methods to the `Map` class in mod-Eluna, enabling developers to retrieve lists of creatures currently present on a map or within a specific area of a map
- **GetCreatures**: Returns a Lua table containing all the current `Creature` objects on the map, 
- **GetCreaturesByAreaId**: Returns a Lua table containing all the `Creature` objects within a specific area ID on the map, indexed by their spawn IDs.
```lua
local map_creatures = player:GetMap():GetCreatures()
for spawn_id, creature in pairs(map_creatures) do
print("Map Creatures",spawn_id, creature)
end
```
```lua
local map_area_creatures= player:GetMap():GetCreaturesByAreaId(9) -- Northshire Valley
for spawn_id, creature in pairs(map_area_creatures) do
print("Map Area Creatures",spawn_id, creature) …
```

Feat(LuaEngine/MapMethods): Add GetCreatures and GetCreaturesByAreaId methods

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/PlayerMethods.h

This pull request introduces 3 new methods to the `Player` class in mod-Eluna, enabling developers to retrieve all player learned spell, teleport player with teleport name or get player homebind.
1. **`GetSpells`**: Retrieve a list of all spells known by a player.
2. **`GetHomebind`**: Access the player’s homebind location.
3. **`TeleportTo`**: Teleport a player to a predefined location (game_tele table).
```lua
local spells = player:GetSpells()
for _, spell_id in pairs(spells) do
print("Learned Spell", spell_id)
end
```
```lua
local player_homebind = player:GetHomebind()
print("Player Homebind", player_homebind.mapId , player_homebind.x, player_homebind.y, player_homebind.z)
```
```lua
player:TeleportTo("Stormwind")
```
```lua
local function OnPlayerLogin(event, player)
local spells = …
```

Feat(LuaEngine/PlayerMethods): Add GetHomebind, GetSpells and TeleportTo

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/UnitMethods.h

This pull request introduces new methods to manage threat levels for units.
1. **`ClearThreat`**: Clears the threat of a specific target from a unit's threat list.
```lua
unit:ClearThreat(target)
```
2. **`ResetAllThreat`**: Resets all threat levels in the unit’s threat list to zero.
```lua
unit:ResetAllThreat()
```
3. **`GetThreat`**: Retrieves the current threat level of a specific target from a unit’s threat list.
```lua
local threat = unit:GetThreat(target)
print(threat)
```

Feat(LuaEngine/UnitMethods): Add GetThreat, ClearThreat, ResetAllThreat methods

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/GlobalMethods.h

This pull request introduces 2 new methods in mod-Eluna, enabling developers to retrieve specific localized gossip_menu option and box_text, get map entrance position.
1. **`GetMapEntrance`**: Returns the entrance position (`x`, `y`, `z`, `o`) for a specified map ID.
2. **`GetGossipMenuOptionLocale`**: Retrieves the localized `OptionText` and `BoxText` for a specific gossip menu option. Falls back to the default text if the specified locale is unavailable.
```lua
local optionText, boxText = GetGossipMenuOptionLocale(1, 2, 3)
print(optionText, boxText)
```
```lua
local x, y, z, o = GetMapEntrance(571)
print(x, y, z, o)
```
```lua
local function OnPlayerLogin(event, player)
local optionText, boxText = GetGossipMenuOptionLocale(10084, 0, 0)
print("Option Menu Locale", optionText, boxText) …
```

feat(LuaEngine/GlobalMethods): add GetGossipMenuOptionLocale, GetMapEntrance

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/PlayerMethods.h

This pull request introduces four new methods in `mod-eluna` for `player`:
- `SetBonusTalentCount`
- `GetBonusTalentCount`
- `AddBonusTalent`
- `RemoveBonusTalent`
> [!WARNING]
> Requires the following dependency:
> - [AzerothCore PR #21271](https://github.com/azerothcore/azerothcore-wotlk/pull/21271)
> [!NOTE]
> Implemented based on feature request: 
> - [mod-eluna Issue #205](https://github.com/azerothcore/mod-eluna/issues/205)
Sets the bonus talent points for a player to a specific value.
```lua
player:SetBonusTalentCount(10)
```
Retrieves the current number of bonus talent points for a player.
```lua
local bonusTalents = player:GetBonusTalentCount()
print(bonusTalents)
```
Adds a specified number of bonus talent points to a player.
```lua
player:AddBonusTalent(5)
```
Removes a …

feat(LuaEngine/PlayerMethods): BonusTalent methods

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/hooks/PlayerHooks.cpp
src/LuaEngine/methods/GlobalMethods.h

This pull request introduces a new Hook in `mod-eluna` for `player`:
- `PLAYER_EVENT_ON_CAN_RESURRECT`
> [!WARNING]
> Requires the following dependency:
> - [AzerothCore PR #21272](https://github.com/azerothcore/azerothcore-wotlk/pull/21272)
```lua
local function OnCanPlayerResurrect(event, player)
return false
end
RegisterPlayerEvent(59, OnCanPlayerResurrect)
```
```lua
local function OnCanPlayerResurrect(event, player)
return false
end
RegisterPlayerEvent(59, OnCanPlayerResurrect)
```
https://github.com/user-attachments/assets/82c5dc1e-40be-49dd-99b8-e6dabed735d5

Feat(LuaEngine/PlayerHooks): Add OnCanPlayerResurrect

---

src/lualib/lua/CMakeLists.txt

Currently, because why not, we are building two libraries:
* lualib
* lualib_static
What's the difference, you ask?
Well, lualib_static is a static library of Lua.
And lualib is either static or shared depending on the magical `LUA_STATIC` flag.
So if `LUA_STATIC` is true by default, congratulations — you now have TWO identical libraries!
Why? I have absolutely no idea.
Obviously, this setup makes no sense whatsoever.
So with this change, we will only have one library, lualib, whose type (static or shared) is properly controlled by `LUA_STATIC`.
Bonus:
Maybe, just maybe, with this fix, the random CI errors in AC when building with modules will finally crawl back to whatever cursed hole they came from. So should fix this issue as well - https://github.com/azerothcore/mod-eluna/issues/268

fix(build/lua): Remove lualib_static from build.

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/CreatureMethods.h
src/LuaEngine/methods/PlayerMethods.h

- Adds GetReactState() to CreatureMethods.h.  This will return if a creature is passive, defensive or aggressive.  Eluna previously had the ability to SetReactState, but it was missing a method for retrieving the current react state.
- Adds GetKnownTaxiNodes() to PlayerMethods.h.  This will return a table of known taxi node IDs that the player has unlocked.
- Adds SetKnownTaxiNodes() to PlayerMethods.h.  This will allow you to set player's known taxi nodes using a table of IDs.
**Example of the new taxi node retrieval:**

Add GetReactState to CreatureMethods and GetKnownTaxiNodes, SetKnownTaxiNodes to PlayerMethods

---

README.md

Updates README to clearly communicate that mod-eluna is no longer compatible with the original Eluna project and provides appropriate guidance for users.
- **Added compatibility warning** highlighting incompatibility with original Eluna scripts
- **Added reference** to ElunaAzerothCore for users needing original Eluna compatibility
- Reduces user confusion about script compatibility
- Provides clear migration path for different use cases
Addresses concerns raised in #289 regarding project direction and compatibility clarity.
Thanks Claude for translation and correction.

README: Clarify mod-eluna independence from original Eluna

---

src/ElunaLuaEngine_SC.cpp
src/LuaEngine/Hooks.h
src/LuaEngine/LuaEngine.h
src/LuaEngine/hooks/ServerHooks.cpp
src/LuaEngine/methods/GlobalMethods.h

To make Handle scripts better handle the OnBeforeConfigLoad event, I added it and moved the execution of Lua scripts directly before the Hook call, otherwise it is useless if no reload is performed. I also separated the OnBefore and OnAfter for the initialization of the World and Configs (which are directly related, so I didn't split this PR into several parts because everything is connected).

 refactor: ServerEvent - OnStartup, OnBeforeConfigLoad, OnConfigLoad

---

src/LuaEngine/methods/LootMethods.h

roll_winner_guid is set when an item has been awarded via Need/Greed/Master, etc.  This ensures that the awarded item goes into the correct player's loot frame.

(LootMethods) - Add roll_winner_guid to GetItems method

---

src/ElunaLuaEngine_SC.cpp

Fixes issue #319
These crashes were introduced with commit 1153fcaef774266b0be74a79373630b7c336fade
This has been tested by me as well as a few other people in the comment thread of the issue.

fix(ElunaLuaEngine): Add nullptr checks to OnDamage and OnHeal methods

---

src/LuaEngine/LuaFunctions.cpp
src/LuaEngine/methods/LootMethods.h

- Currently we can GetItems() via loot->items.size(), but this does not include quest items.  This PR adds support for quest items now via GetQuestItems() and updating a few other methods to also include quest items in their logic.
- I also added an additional bool parameter to the AddItem() method for allowing items to be stacked as shown in the below screenshot.  I am working on an aoe loot lua script and having the option for items be stackable is very useful.
In the screenshot below, we can see stackable items with the bool true and the ability to merge quest items as well.

feat(LootMethods): Add support for adding/retrieving quest items and item stacking
