azerothcore/mod-eluna

- PlayerMethods.h
- UnitMethods.h
Required after https://github.com/azerothcore/azerothcore-wotlk/pull/8708
> fix(UnitMethods): GetFaction/SetFaction case update

- LuaFunctions.cpp
- PlayerMethods.h
`Player:GetMailItem(guid)`: Returns a mailed `Item` by guid.
> feat(PlayerMethods): expose GetMItem

- libs/rigtorp/SPSCQueue.h
> fix(macOS): build

- GroupMethods.h
- LuaFunctions.cpp
Expose the IsLFGGroup to Eluna
> feat(GroupMethods): Expose IsLFGGroup()

- .github/workflows/build.yml
- CreatureMethods.h
This reverts commit f9d57429d63ffd0d759fcac3a680f4a32b9a8c9d, reversing
changes made to ccf337262c2573f345e54b2973678f5dbf282aa2.
> Revert "Merge branch 'ElunaLuaEngine:master' into master"

- ElunaInstanceAI.cpp
- ElunaTemplate.h
- GlobalMethods.h
- HttpManager.cpp
- LuaEngine.cpp
- https://github.com/azerothcore/azerothcore-wotlk/pull/10366
> feat(Logging): add support new logging

- HttpManager.cpp
- LuaEngine.h
- PlayerHooks.cpp
Introduces the changes made on https://github.com/azerothcore/azerothcore-wotlk/pull/10471
And also fix build on master :)
> Fix(Hooks): Update OnReputationChange method

- .github/workflows/create-pr.sh
- .github/workflows/documentation.yml
This adds a Github action to automatically push the changes made to the documentation to [azerothcore/azerothcore.github.io](https://github.com/azerothcore/azerothcore.github.io/tree/master/pages/eluna) in the form of a pull request
> ci: create documentation pr to website repo

- ElunaQueryMethods.h
- PlayerMethods.h
https://github.com/azerothcore/azerothcore-wotlk/pull/10211
> feat(DBLayer): add support new db api

- GlobalMethods.h
Opened on request from @UltraNix
> fix: TaxiBuildfix.

- GossipHooks.cpp
Cherry pick from https://github.com/ElunaLuaEngine/Eluna/pull/405
Co-authored by https://github.com/Rochet2
> fix: restore gossip menu after lua script

- src/LuaEngine/ElunaCreatureAI.h
https://github.com/azerothcore/azerothcore-wotlk/pull/10525
> AreaBoundary EvadeReason

- src/ElunaLuaEngine_SC.cpp
Closes #43 
And yes, tested as well with the scripts provided by the issue :)
> fix: GameEvent Hooks

- src/LuaEngine/CreatureMethods.h
- src/LuaEngine/UnitMethods.h
Related to https://github.com/azerothcore/azerothcore-wotlk/pull/12992
> refactor(Eluna): Fix code style for threat system

- src/LuaEngine/UnitMethods.h
This reverts commit 1adf4f371e88040e7b788f7ddbef62b70887b45e.
> Revert "fix: build after qAston (#66)"

- src/LuaEngine/LuaFunctions.cpp
- src/LuaEngine/PlayerMethods.h
Adds `Player:GetXP()`:
> Returns the player's experience points.
> feat: add Player:GetXP()

- README.md
- src/LuaEngine/GroupMethods.h
- src/LuaEngine/LuaFunctions.cpp
Adds `Group:GetGroupType()`:
> Returns the type of this [`Group`](https://www.azerothcore.org/pages/eluna/Group/index.html)
**Requires https://github.com/azerothcore/azerothcore-wotlk/pull/14411**
> feat: add Group:GetGroupType()

- src/LuaEngine/ElunaCreatureAI.h
https://github.com/azerothcore/azerothcore-wotlk/pull/15026
> EnterCombat -> JustEngagedWith

- src/LuaEngine/LuaFunctions.cpp
Fixes https://github.com/azerothcore/mod-eluna/issues/57
cc @noisiver
> fix: do not garbage collect AchievementEntry

- src/LuaEngine/AchievementMethods.h
- src/LuaEngine/LuaFunctions.cpp
```lua
local function OnPlayerAchievementComplete (event, player, achievement)
if achievement ~= nil and achievement:GetId() ~= 0 then
print(player:GetName() .. " earned \"" .. achievement:GetName() .. "\"")
end
end
RegisterPlayerEvent(45, OnPlayerAchievementComplete)
```
> feat: add AchievementEntry:GetName()

- src/LuaEngine/UnitMethods.h
Reverts azerothcore/mod-eluna#129
cf https://github.com/azerothcore/azerothcore-wotlk/pull/16114
> Revert "fix compile error"

- README.md
- src/LuaEngine/LuaFunctions.cpp
- src/LuaEngine/PlayerMethods.h
Implemented Player:CanRewardQuest(questId) as well as Player:CanCompleteRepeatableQuest(questId).
checked both with a print statement if it does work correct and they worked just fine =)
> Feature: Added player:CanRewardQuest(questId)/player:CanCompleteRepeatableQuest(questId)

- src/LuaEngine/libs/httplib.h
Should fix https://github.com/ElunaLuaEngine/Eluna/issues/437
> feat(libs): update httplib

- src/ElunaLuaEngine_SC.cpp
If https://github.com/azerothcore/azerothcore-wotlk/pull/19081 merges then this change will be required.
Testable with this Lua script:
```lua
local PLAYER_EVENT_ON_COMMAND = 42
RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, function(event, player, command)
player:SendBroadcastMessage("You ran command " .. command)
end)
```
> Update OnCommand for core hook changes.

- src/ElunaLuaEngine_SC.cpp
- this should now properly overwrite the instanceData pointer
- Requires https://github.com/azerothcore/azerothcore-wotlk/pull/19252
- maybe makes Progress #49
> fix OnBeforeCreateInstanceScript() hook

- src/LuaEngine/PlayerMethods.h
Re https://github.com/azerothcore/azerothcore-wotlk/pull/20926
> Add fmt formatting to SendAreaTriggerMessage

- .github/workflows/build-lua52.yml
- .github/workflows/build-luajit.yml
- .github/workflows/core-build-base.yml
> Fix(Workflow): Fix github action when PR is sending

- conf/mod_eluna.conf.dist
- src/LuaEngine/LuaEngine.cpp
- src/LuaEngine/LuaEngine.h
Related to :
- https://github.com/ElunaLuaEngine/Eluna/commit/6416a8d99c4eb2b68efc0bc9cb14791a43465a85
- https://github.com/ElunaLuaEngine/Eluna/commit/a60f1eaf8ab48340f41f36362e11989821b1c61d
> Add support for externe lib and moonscript

- src/LuaEngine/methods/SpellEntryMethods.h
This pull request introduces comments for 33 of the SpellEntryMethods.
> chore(LuaEngine): added comments to SpellEntryMethods.

- src/LuaEngine/methods/GuildMethods.h
Related to this -> https://github.com/azerothcore/mod-eluna/issues/252#issuecomment-2635200443
> chore(doxygen): fix documentation generation

- .github/workflows/core-build-base.yml
- src/LuaEngine/lmarshal.cpp
- src/LuaEngine/methods/MapMethods.h
follow-up to #220 which disabled `-Werror' for CI build
> fix(CI): re-enable -Werror compile flag

- src/LuaEngine/ElunaIncludes.h
- src/LuaEngine/LuaEngine.cpp
- src/LuaEngine/methods/GlobalMethods.h
Fix for https://github.com/azerothcore/azerothcore-wotlk/commit/edcfaeb845c312bf8759e27589b3aeee85975052
> chore: update to support WorldSessionMgr PR 21400

- src/ElunaLuaEngine_SC.cpp
azerothcore/azerothcore-wotlk#21020
> Update ElunaLuaEngine_SC.cpp - fix build

- src/ElunaLuaEngine_SC.cpp
This PR limits the execution of core hooks to those explicitly listed in https://github.com/azerothcore/mod-eluna/tree/master/src/ElunaLuaEngine_SC.cpp
Future additions of features will potentially require adding more hooks to that list.
> add enabled hook lists for performance improvement

- src/LuaEngine/methods/UnitMethods.h
- src/LuaEngine/methods/WorldObjectMethods.h
Fix for https://github.com/azerothcore/azerothcore-wotlk/pull/22595 once merged to master
> Sync AC Grid PR changes

- src/LuaEngine/methods/PlayerMethods.h
Fix the problem https://github.com/azerothcore/mod-eluna/issues/308
> Fix player AdvanceSkill method crash

- src/ElunaLuaEngine_SC.cpp
Related to https://github.com/azerothcore/mod-eluna/issues/157
> Fix: OnQuestReward GameObject
